[package]
name = "sessions"
version = "0.1.0"
authors = ["Alexander Jackson <alexanderjackson@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4"
serde = "1"
serde_derive = "1"
lettre = "0.10.0-alpha.2"
dotenv = "0.15"
rand = "0.7"
chrono = "0.4.19"

[dependencies.rocket_contrib]
version = "0.4"
features = ["tera_templates", "diesel_sqlite_pool"]

[dependencies.diesel]
version = "1.3"
features = ["sqlite", "r2d2"]
