[package]
name = "blackboards"
version = "0.1.0"
authors = ["Alexander Jackson <alexanderjackson@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4"
serde = "1"
serde_derive = "1"
lettre = "0.10.0-alpha.5"
dotenv = "0.15"
rand = "0.8"
chrono = "0.4.19"
url = "2.2.1"

[dependencies.rocket_contrib]
version = "0.4"
features = ["tera_templates", "diesel_sqlite_pool"]

[dependencies.diesel]
version = "1.3"
features = ["sqlite", "r2d2"]

[dependencies.oauth]
version = "0.4"
package = "oauth1-request"

[dependencies.reqwest]
version = "0.11.0"
features = ["blocking"]
