[package]
name = "blackboards"
version = "0.1.0"
authors = ["Alexander Jackson <alexanderjackson@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.125"
serde_derive = "1.0.125"
dotenv = "0.15.0"
rand = "0.8.3"
chrono = "0.4.19"
url = "2.2.1"
itertools = "0.10.0"
either = "1.6.1"
log = "0.4.14"
base64 = "0.13.0"
reqwest = "0.11.3"
diesel-derive-newtype = "0.1.2"

[dependencies.rocket]
git = "https://github.com/SergioBenitez/Rocket"
branch = "master"
features = ["secrets"]

[dependencies.rocket_contrib]
git = "https://github.com/SergioBenitez/Rocket"
branch = "master"
features = ["tera_templates", "diesel_postgres_pool"]

[dependencies.diesel]
version = "1.4.6"
features = ["postgres", "r2d2"]

[dependencies.lettre]
version = "0.10.0-beta.3"
features = ["smtp-transport", "tokio1", "tokio1-native-tls"]

[dependencies.oauth]
version = "0.5.0"
package = "oauth1-request"

[dependencies.tallystick]
git = "https://github.com/phayes/tallystick"
branch = "master"
features = ["nightly"]

[dependencies.fern]
version = "0.6.0"
features = ["colored"]
