name: cargo build

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install nightly compiler
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        default: true

    - name: cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build
