name: cargo test

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: cargo test
    - uses: actions/checkout@v2
    - run: cargo test
